<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <RestoreLockedMode Condition="Exists('$(MSBuildThisFileDirectory)packages.lock.json')">true</RestoreLockedMode>
    <NuGetAudit>true</NuGetAudit>
  </PropertyGroup>
</Project>
