<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ClearHaul.BackupCli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <ProjectReference Include="..\..\src\ClearHaul.Backup\ClearHaul.Backup.csproj" />
  </ItemGroup>
</Project>
